name: 🔄 Update Telegram Proxies

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # مجوز مستقیم نوشتن و کامیت در ریپو

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install requests

      - name: 📄 Setup Folders
        run: |
          mkdir -p countries
          touch countries/.gitkeep
          touch sub.txt

      - name: 👾 Run MTProto Scraper
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
        run: |
          python scraper.py

      - name: 🚀 Commit and Push
        run: |
          git config --global user.name "Proxy Hunter Bot 🤖"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add sub.txt countries/
          git diff --staged --quiet || (git commit -m "🤖 Auto-update MTProto Proxies: $(date +'%Y-%m-%d %H:%M')" && git push)
